### ISSUE TITLE
Twitch Emotes don´t work "on their own"

### ISSUE THREAD

**Issue by FILXxL** [jahaanjain/Emote-Overlay#1]
Hi!

I don´t know if it´s a bug or a feature...but the Twitch Emotes do not work on their own. They only get recognized when there´s a message along with the emote. BTTV emotes work on their own.

**Comment by jahaanjain** [comment]
It seems like it's working on my side, using a default global Twitch Emote with no message other then the emote:
![Streaks](https://i.imgur.com/e4fJUvj.png)
![Chat](https://i.imgur.com/aF7auzE.png)

**Comment by FILXxL** [comment]
mhm...funny! I tried now with a global emote...and it still only recognizes if theres atleast one emote that has a message along it. (also if its only just one letter). 

Do you have any parameters in the url? I use the "default" url

**Comment by jahaanjain** [comment]
> mhm...funny! I tried now with a global emote...and it still only recognizes if theres atleast one emote that has a message along it. (also if its only just one letter).

Could you show me the messages you are sending and the URL you are using?

**Comment by FILXxL** [comment]
Yeah ofc

my url: https://api.roaringiron.com/emoteoverlay?channel=hug000

The emotes I tested were "hug000STONKS" (channel emote) and "4Head" (global emote)

Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS
Hug000: hug000STONKS X
Hug000: hug000STONKS s
Hug000: hug000STONKS
Hug000: hug000STONKS w
Hug000: hug000STONKS fg

(here it showed a 5x streak...and counting afterwards)

Hug000: hug000STONKS sa
Hug000: hug000STONKS
Hug000: hug000STONKS

(8xstreak)


Hug000: 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head

(nothing until here)

Hug000: s 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head
Hug000: 4Head

(5x streak again)



Hope this helps you.

**Comment by jahaanjain** [comment]
Weird, it's working on my side with both global emotes and sub emotes.
Can you try using the URL on your browser in incognito mode?
What version of OBS are you using?

Global:
![Streak](https://i.imgur.com/L750lZX.png)
![Chat](https://i.imgur.com/91AMYFk.png)

Sub Emote:
![Streak](https://i.imgur.com/S0fQcp6.png)
![Chat](https://i.imgur.com/4ESgv0l.png)

**Comment by FILXxL** [comment]
I´m using OBS 27.1.3 on Windows.

And trying it in Incognito Mode in Brave and Google Chrome lead to the same results...only if I send a letter with it the emote gets recognized!

**Comment by jahaanjain** [comment]
Found the issue and it has been fixed! 👍

**Comment by FILXxL** [comment]
It works!!! Thank you so much!
