### ISSUE TITLE
Animated Twitch Subscriber emotes are not animated in the overlay

### ISSUE THREAD

**Issue by moshsh** [jahaanjain/Emote-Overlay#2]
In June, Twitch introduced animated channel emotes.
It seems like the overlay isn't showing these in animated form, only the first frame. 

Here's an example of an animated emote (beniceHEY) from the channel benice92 

https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_f5572a61e2e44abc994c530901e8dbdc/default/dark/2.0

Animated emotes for BTTV and 7TV are working correctly as far as I can tell

**Comment by jahaanjain** [comment]
Animated subscriber emotes from Twitch seem to be working correctly on my side. Could you send me the URL you are using?

**Comment by moshsh** [comment]
https://api.roaringiron.com/emoteoverlay?channel=slicedfred&minStreak=3&7tv=1&showEmoteSizeMultiplier=4

**Comment by jahaanjain** [comment]
Tried the link and animated Twitch emotes are working for me. Could you try in an incognito browser?

**Comment by moshsh** [comment]
I should have specified I meant the showemote part of the overlay, the emote streaks are working

**Comment by jahaanjain** [comment]
Should be fixed now! Thanks!
