### ISSUE TITLE
Stopped working (Proxy Error)

### ISSUE THREAD

**Issue by Umbreee** [jahaanjain/Emote-Overlay#4]
Opening the link or using the link as a browser source gives this error:

> Proxy Error
> The proxy server could not handle the request
> Reason: Error during SSL Handshake with remote server
> 
> Apache/2.4.29 (Ubuntu) Server at api.roaringiron.com Port 443

Everything has worked fine before yesterday

**Comment by jahaanjain** [comment]
Should be fixed now, thanks for letting me know.
