### ISSUE TITLE
Location Config

### ISSUE THREAD

**Issue by Anscenic1** [jahaanjain/Emote-Overlay#6]
just would be cool that you can choose where the emote combo appears, for example : &Location=
1 (Top left)
2 (Top Right)
3 (Botton Left) as default
4 (Botton Right)
5(center for the weird ones)

**Comment by jahaanjain** [comment]
Great suggestion! Could you make a PR with these changes for me to review?

**Comment by Anscenic1** [comment]
Sorry, can you explain me what a PR means? then i can work on it :D
