### ISSUE TITLE
Doesn't work witn 7TV + error getting FFZ emotes

### ISSUE THREAD

**Issue by m00t01** [jahaanjain/Emote-Overlay#7]
![image](https://user-images.githubusercontent.com/108951614/178046586-3e41b37d-3b53-4732-b0c1-3a902e773766.png)
Error getting ffz doesn't show on OBS, when pasting the link onto browset it says that

Also doesn't work with 7TV, tried a lot and wont work
![image](https://user-images.githubusercontent.com/108951614/178046792-932a2410-42b1-41d0-b4a1-0ac44af648cc.png)

hope u can help

**Comment by jahaanjain** [comment]
Hey @m00t01, what is the Twitch channel you are using? And can you send me the URL you are using?
