### ISSUE TITLE
No input sanitization for emoteStreakEndingText

### ISSUE THREAD

**Issue by nickelyn** [jahaanjain/Emote-Overlay#8]
**Reflected XSS:** JavaScript can be injected in the URL to show NSFW stuff. Very low impact as it would require the streamer to click the link, but given it is your website they might feel inclined to do so?
https://github.com/jahaanjain/Emote-Overlay/blob/a8b273f928969d10e7cb25fc97ce5bc8c8028b9f/main.js#L12
https://github.com/jahaanjain/Emote-Overlay/blob/a8b273f928969d10e7cb25fc97ce5bc8c8028b9f/main.js#L210

**Comment by jahaanjain** [comment]
Thanks for opening the ticket! I've resolved this in the latest commit.
